services:
  app:
    depends_on:
      - db
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NEXT_PUBLIC_CLIENTVAR: "lgUFqiPvK47E2Z27FPevBQXBR8wBXvh6NEpyQ5yxgph5Cw=="
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@127.0.0.1:5432/${POSTGRES_DB}
