FROM node:lts-alpine

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN corepack enable pnpm && pnpm install --frozen-lockfile

COPY . .

EXPOSE 3000

ENV NODE_ENV=development

CMD ["pnpm", "dev"]
