FROM node:lts-alpine

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN corepack enable pnpm && pnpm install --frozen-lockfile

EXPOSE 3000

ENV NODE_ENV=development
ENV NEXT_TELEMENTRY_DISABLED=1

ENV WATCHPACK_POLLING=true

CMD ["pnpm", "dev"]
